version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"
    environment:
      - VUE_APP_API_URL=http://backend:8000
